ALTER TABLE analyses ADD COLUMN IF NOT EXISTS progress_step INTEGER;
ALTER TABLE analyses ADD COLUMN IF NOT EXISTS progress_total INTEGER;
ALTER TABLE analyses ADD COLUMN IF NOT EXISTS progress_message TEXT;
ALTER TABLE analyses ADD COLUMN IF NOT EXISTS progress_updated_at TIMESTAMP;

ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS system_name VARCHAR(128) NOT NULL DEFAULT '履职系统';
ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS tagline VARCHAR(255) NOT NULL DEFAULT 'SOP 视觉核验';
ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS company_name VARCHAR(128);
ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS copyright TEXT NOT NULL DEFAULT '© 履职系统';
ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS theme_color VARCHAR(32) NOT NULL DEFAULT '#0f766e';
ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS logo_blob_key VARCHAR(600);
ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS login_image_blob_key VARCHAR(600);
