ALTER TABLE cameras ADD COLUMN IF NOT EXISTS lng DOUBLE PRECISION;
ALTER TABLE cameras ADD COLUMN IF NOT EXISTS lat DOUBLE PRECISION;
ALTER TABLE cameras ADD COLUMN IF NOT EXISTS device_kind VARCHAR(32) NOT NULL DEFAULT 'camera';
ALTER TABLE cameras ADD COLUMN IF NOT EXISTS stream_protocol VARCHAR(32) NOT NULL DEFAULT 'rtsp';
